export interface DirectoryServer {
  slug: string;
  name: string;
  url: string;
  transport: "http" | "sse";
  auth: "oauth" | "bearer" | "none";
  category: string;
  description: string;
  publisher: string;
  official: boolean;
}

export const DIRECTORY: readonly DirectoryServer[] = [
  {
    "slug": "ahrefs",
    "name": "Ahrefs",
    "url": "https://api.ahrefs.com/mcp/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Search",
    "description": "SEO and backlink analytics from Ahrefs for keyword, domain, and competitor research.",
    "publisher": "Ahrefs",
    "official": true
  },
  {
    "slug": "airtable",
    "name": "Airtable",
    "url": "https://mcp.airtable.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Database",
    "description": "Airtable MCP server for bases, tables, and records.",
    "publisher": "Airtable",
    "official": true
  },
  {
    "slug": "airwallex",
    "name": "Airwallex",
    "url": "https://mcp-demo.airwallex.com/developer",
    "transport": "http",
    "auth": "none",
    "category": "Finance",
    "description": "Airwallex MCP server for payments and financial platform capabilities.",
    "publisher": "Airwallex",
    "official": true
  },
  {
    "slug": "alltrails",
    "name": "AllTrails",
    "url": "https://www.alltrails.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Other",
    "description": "AllTrails MCP server for trail discovery and outdoor activity data.",
    "publisher": "AllTrails",
    "official": true
  },
  {
    "slug": "amplitude",
    "name": "Amplitude",
    "url": "https://mcp.amplitude.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Marketing",
    "description": "Amplitude MCP server for product and behavioral analytics.",
    "publisher": "Amplitude",
    "official": true
  },
  {
    "slug": "asana",
    "name": "Asana",
    "url": "https://mcp.asana.com/v2/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Productivity",
    "description": "Official Asana remote MCP server for tasks, projects, and workspace data.",
    "publisher": "Asana",
    "official": true
  },
  {
    "slug": "atlassian",
    "name": "Atlassian",
    "url": "https://mcp.atlassian.com/v1/mcp/authv2",
    "transport": "http",
    "auth": "oauth",
    "category": "Productivity",
    "description": "Atlassian remote MCP server for Jira, Confluence, and Compass.",
    "publisher": "Atlassian",
    "official": true
  },
  {
    "slug": "audible",
    "name": "Audible",
    "url": "https://mcp.audible.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Other",
    "description": "Audible MCP server for audiobook catalog and library data.",
    "publisher": "Audible",
    "official": true
  },
  {
    "slug": "autodesk-product-help",
    "name": "Autodesk Product Help",
    "url": "https://developer.api.autodesk.com/knowledge/public/v1/mcp",
    "transport": "http",
    "auth": "none",
    "category": "Development",
    "description": "Read-only access to Autodesk product documentation across 110+ products.",
    "publisher": "Autodesk",
    "official": true
  },
  {
    "slug": "aws-marketplace",
    "name": "AWS Marketplace",
    "url": "https://marketplace-mcp.us-east-1.api.aws/",
    "transport": "http",
    "auth": "none",
    "category": "Cloud",
    "description": "Search and explore AWS Marketplace products and listings.",
    "publisher": "AWS",
    "official": true
  },
  {
    "slug": "blockscout",
    "name": "Blockscout",
    "url": "https://mcp.blockscout.com/mcp",
    "transport": "http",
    "auth": "none",
    "category": "Finance",
    "description": "Query blockchain data via the Blockscout block explorer.",
    "publisher": "Blockscout",
    "official": true
  },
  {
    "slug": "box",
    "name": "Box",
    "url": "https://mcp.box.com",
    "transport": "http",
    "auth": "oauth",
    "category": "Cloud",
    "description": "Box MCP server for content management and file access.",
    "publisher": "Box",
    "official": true
  },
  {
    "slug": "bucket",
    "name": "Bucket Feature Flags",
    "url": "https://app.bucket.co/api/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Development",
    "description": "Manage and flag features directly from chat via Bucket's feature-flag platform.",
    "publisher": "Bucket",
    "official": false
  },
  {
    "slug": "canva",
    "name": "Canva",
    "url": "https://mcp.canva.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Design",
    "description": "Canva MCP server for working with designs and brand assets.",
    "publisher": "Canva",
    "official": true
  },
  {
    "slug": "carta",
    "name": "Carta",
    "url": "https://mcp.app.carta.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Finance",
    "description": "Access cap table and equity management data from Carta.",
    "publisher": "Carta",
    "official": true
  },
  {
    "slug": "cb-insights",
    "name": "CB Insights",
    "url": "https://mcp.cbinsights.com",
    "transport": "http",
    "auth": "oauth",
    "category": "Finance",
    "description": "Market and company intelligence from CB Insights.",
    "publisher": "CB Insights",
    "official": true
  },
  {
    "slug": "clarify",
    "name": "Clarify",
    "url": "https://api.clarify.ai/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Other",
    "description": "Clarify AI CRM integration via its hosted MCP endpoint.",
    "publisher": "Clarify",
    "official": true
  },
  {
    "slug": "clerk",
    "name": "Clerk",
    "url": "https://mcp.clerk.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Development",
    "description": "User authentication and management via Clerk.",
    "publisher": "Clerk",
    "official": true
  },
  {
    "slug": "clickup",
    "name": "ClickUp",
    "url": "https://mcp.clickup.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Productivity",
    "description": "Task and project management via ClickUp.",
    "publisher": "ClickUp",
    "official": true
  },
  {
    "slug": "clockwise",
    "name": "Clockwise",
    "url": "https://mcp.getclockwise.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Productivity",
    "description": "Smart calendar and schedule optimization via Clockwise.",
    "publisher": "Clockwise",
    "official": true
  },
  {
    "slug": "cloudflare",
    "name": "Cloudflare",
    "url": "https://mcp.cloudflare.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Cloud",
    "description": "Cloudflare's official MCP server for managing Cloudflare resources and configuration.",
    "publisher": "Cloudflare",
    "official": true
  },
  {
    "slug": "cloudinary",
    "name": "Cloudinary",
    "url": "https://asset-management.mcp.cloudinary.com/sse",
    "transport": "sse",
    "auth": "oauth",
    "category": "Design",
    "description": "Upload, manage, transform, and deliver image and video assets.",
    "publisher": "Cloudinary",
    "official": true
  },
  {
    "slug": "coindesk",
    "name": "CoinDesk",
    "url": "https://mcp.coindesk.com/mcp",
    "transport": "http",
    "auth": "none",
    "category": "Finance",
    "description": "Crypto market data and indices from CoinDesk Data and Indices.",
    "publisher": "CoinDesk",
    "official": true
  },
  {
    "slug": "consensus",
    "name": "Consensus",
    "url": "https://mcp.consensus.app/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Search",
    "description": "AI-powered scientific research search from Consensus.",
    "publisher": "Consensus",
    "official": true
  },
  {
    "slug": "contentsquare",
    "name": "Contentsquare",
    "url": "https://api.contentsquare.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Marketing",
    "description": "Digital experience analytics from Contentsquare.",
    "publisher": "Contentsquare",
    "official": true
  },
  {
    "slug": "context7",
    "name": "Context7",
    "url": "https://mcp.context7.com/mcp",
    "transport": "http",
    "auth": "none",
    "category": "Development",
    "description": "Up-to-date code examples and library documentation for LLMs.",
    "publisher": "Context7",
    "official": true
  },
  {
    "slug": "coupler-io",
    "name": "Coupler.io",
    "url": "https://mcp.coupler.io/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Database",
    "description": "Data integration and reporting automation via Coupler.io.",
    "publisher": "Coupler.io",
    "official": true
  },
  {
    "slug": "courtlistener",
    "name": "CourtListener",
    "url": "https://mcp.courtlistener.com/",
    "transport": "http",
    "auth": "none",
    "category": "Search",
    "description": "Legal research and case law search from the Free Law Project.",
    "publisher": "Free Law Project",
    "official": true
  },
  {
    "slug": "craft",
    "name": "Craft",
    "url": "https://mcp.craft.do/my/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Productivity",
    "description": "Document and note management via Craft.",
    "publisher": "Craft",
    "official": true
  },
  {
    "slug": "crossbeam",
    "name": "Crossbeam",
    "url": "https://mcp.crossbeam.com",
    "transport": "http",
    "auth": "oauth",
    "category": "Marketing",
    "description": "Partner ecosystem and account mapping data from Crossbeam.",
    "publisher": "Crossbeam",
    "official": true
  },
  {
    "slug": "crypto-com",
    "name": "Crypto.com",
    "url": "https://mcp.crypto.com/market-data/mcp",
    "transport": "http",
    "auth": "none",
    "category": "Finance",
    "description": "Crypto market data from Crypto.com.",
    "publisher": "Crypto.com",
    "official": true
  },
  {
    "slug": "daloopa",
    "name": "Daloopa",
    "url": "https://mcp.daloopa.com/server/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Finance",
    "description": "Financial statement and fundamentals data from Daloopa.",
    "publisher": "Daloopa",
    "official": true
  },
  {
    "slug": "datasite",
    "name": "Datasite",
    "url": "https://mcp.global.datasite.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Finance",
    "description": "M&A deal and virtual data room management via Datasite.",
    "publisher": "Datasite",
    "official": true
  },
  {
    "slug": "day-ai",
    "name": "Day AI",
    "url": "https://day.ai/api/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Marketing",
    "description": "Prospect and customer intelligence via Day AI's CRM context.",
    "publisher": "Day AI",
    "official": true
  },
  {
    "slug": "digits",
    "name": "Digits",
    "url": "https://api.digits.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Finance",
    "description": "Accounting and financial data from Digits.",
    "publisher": "Digits",
    "official": true
  },
  {
    "slug": "doordash",
    "name": "DoorDash",
    "url": "https://openapi.doordash.com/mcp/consumer",
    "transport": "http",
    "auth": "oauth",
    "category": "Other",
    "description": "Consumer food ordering and delivery via DoorDash.",
    "publisher": "DoorDash",
    "official": true
  },
  {
    "slug": "dovetail",
    "name": "Dovetail",
    "url": "https://dovetail.com/api/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Productivity",
    "description": "Customer research and insights repository from Dovetail.",
    "publisher": "Dovetail",
    "official": true
  },
  {
    "slug": "edgeone-pages",
    "name": "EdgeOne Pages",
    "url": "https://mcp-on-edge.edgeone.site/mcp-server",
    "transport": "http",
    "auth": "none",
    "category": "Cloud",
    "description": "Deploy HTML content to Tencent EdgeOne Pages and get a public URL.",
    "publisher": "Tencent EdgeOne",
    "official": false
  },
  {
    "slug": "egnyte",
    "name": "Egnyte",
    "url": "https://mcp-server.egnyte.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Cloud",
    "description": "Content management and file storage from Egnyte.",
    "publisher": "Egnyte",
    "official": true
  },
  {
    "slug": "enterpret",
    "name": "Enterpret",
    "url": "https://wisdom-api.enterpret.com/server/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Productivity",
    "description": "Customer feedback analytics from Enterpret.",
    "publisher": "Enterpret",
    "official": true
  },
  {
    "slug": "eraser",
    "name": "Eraser",
    "url": "https://app.eraser.io/api/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Design",
    "description": "Diagrams and design docs from Eraser.",
    "publisher": "Eraser",
    "official": true
  },
  {
    "slug": "exa",
    "name": "Exa",
    "url": "https://mcp.exa.ai/mcp",
    "transport": "http",
    "auth": "bearer",
    "category": "Search",
    "description": "Web search and research via Exa.",
    "publisher": "Exa",
    "official": true
  },
  {
    "slug": "expedia",
    "name": "Expedia",
    "url": "https://www.expedia.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Other",
    "description": "Travel booking and trip planning from Expedia.",
    "publisher": "Expedia",
    "official": true
  },
  {
    "slug": "fathom",
    "name": "Fathom",
    "url": "https://api.fathom.ai/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Productivity",
    "description": "Meeting recordings, transcripts, and summaries from Fathom.",
    "publisher": "Fathom",
    "official": true
  },
  {
    "slug": "figma",
    "name": "Figma",
    "url": "https://mcp.figma.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Design",
    "description": "Figma remote MCP server for design files and design context.",
    "publisher": "Figma",
    "official": true
  },
  {
    "slug": "fmp",
    "name": "FMP",
    "url": "https://financialmodelingprep.com/mcp",
    "transport": "http",
    "auth": "bearer",
    "category": "Finance",
    "description": "Market data and financial statements from Financial Modeling Prep.",
    "publisher": "Financial Modeling Prep",
    "official": true
  },
  {
    "slug": "github",
    "name": "GitHub",
    "url": "https://api.githubcopilot.com/mcp/",
    "transport": "http",
    "auth": "oauth",
    "category": "Development",
    "description": "GitHub's official MCP server providing structured repository context.",
    "publisher": "GitHub",
    "official": true
  },
  {
    "slug": "gitlab",
    "name": "GitLab",
    "url": "https://gitlab.com/api/v4/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Development",
    "description": "Source control and CI/CD from GitLab.",
    "publisher": "GitLab",
    "official": true
  },
  {
    "slug": "gocardless",
    "name": "GoCardless",
    "url": "https://mcp.gocardless.com",
    "transport": "http",
    "auth": "oauth",
    "category": "Finance",
    "description": "Bank payments and direct debit from GoCardless.",
    "publisher": "GoCardless",
    "official": true
  },
  {
    "slug": "godaddy",
    "name": "GoDaddy",
    "url": "https://api.godaddy.com/v1/domains/mcp",
    "transport": "http",
    "auth": "bearer",
    "category": "Cloud",
    "description": "Domain registration and management from GoDaddy.",
    "publisher": "GoDaddy",
    "official": true
  },
  {
    "slug": "goodnotes",
    "name": "Goodnotes",
    "url": "https://claude-mcp-api.ml.goodnotes.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Productivity",
    "description": "Note-taking and handwriting from Goodnotes.",
    "publisher": "Goodnotes",
    "official": true
  },
  {
    "slug": "bigquery",
    "name": "Google Cloud BigQuery",
    "url": "https://bigquery.googleapis.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Database",
    "description": "Serverless data warehouse queries via Google Cloud BigQuery.",
    "publisher": "Google Cloud",
    "official": true
  },
  {
    "slug": "grain",
    "name": "Grain",
    "url": "https://api.grain.com/_/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Productivity",
    "description": "Meeting recording and notes from Grain.",
    "publisher": "Grain",
    "official": true
  },
  {
    "slug": "granola",
    "name": "Granola",
    "url": "https://mcp.granola.ai/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Productivity",
    "description": "AI meeting notepad and meeting memory from Granola.",
    "publisher": "Granola",
    "official": true
  },
  {
    "slug": "graphos-tools",
    "name": "GraphOS (Apollo)",
    "url": "https://mcp.apollographql.com",
    "transport": "http",
    "auth": "oauth",
    "category": "Development",
    "description": "GraphQL schema and GraphOS tooling from Apollo.",
    "publisher": "Apollo GraphQL",
    "official": true
  },
  {
    "slug": "harmonic",
    "name": "Harmonic",
    "url": "https://mcp.api.harmonic.ai",
    "transport": "http",
    "auth": "oauth",
    "category": "Finance",
    "description": "Startup and company intelligence data from Harmonic.",
    "publisher": "Harmonic",
    "official": true
  },
  {
    "slug": "hex",
    "name": "Hex",
    "url": "https://app.hex.tech/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Database",
    "description": "Collaborative data notebooks and analytics from Hex.",
    "publisher": "Hex",
    "official": true
  },
  {
    "slug": "honeycomb",
    "name": "Honeycomb",
    "url": "https://mcp.honeycomb.io/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Development",
    "description": "Observability and distributed tracing from Honeycomb.",
    "publisher": "Honeycomb",
    "official": true
  },
  {
    "slug": "httpstatus",
    "name": "HttpStatus",
    "url": "https://mcp.httpstatus.com/mcp",
    "transport": "http",
    "auth": "bearer",
    "category": "Development",
    "description": "Look up and explain HTTP status codes and related diagnostics.",
    "publisher": "HttpStatus",
    "official": false
  },
  {
    "slug": "hubspot",
    "name": "HubSpot",
    "url": "https://mcp.hubspot.com",
    "transport": "http",
    "auth": "oauth",
    "category": "Marketing",
    "description": "HubSpot MCP server for CRM, marketing, and sales data.",
    "publisher": "HubSpot",
    "official": true
  },
  {
    "slug": "huggingface",
    "name": "Hugging Face",
    "url": "https://huggingface.co/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Development",
    "description": "Models, datasets, and Spaces from Hugging Face.",
    "publisher": "Hugging Face",
    "official": true
  },
  {
    "slug": "ifttt",
    "name": "IFTTT",
    "url": "https://ifttt.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Other",
    "description": "Automation and app-integration applets via IFTTT.",
    "publisher": "IFTTT",
    "official": true
  },
  {
    "slug": "imanage",
    "name": "iManage Work",
    "url": "https://cloudimanage.com/mcp/work",
    "transport": "http",
    "auth": "oauth",
    "category": "Productivity",
    "description": "Document and email management for iManage Work.",
    "publisher": "iManage",
    "official": true
  },
  {
    "slug": "instacart",
    "name": "Instacart",
    "url": "https://fig-mcp.instacart.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Other",
    "description": "Grocery search and ordering via Instacart.",
    "publisher": "Instacart",
    "official": true
  },
  {
    "slug": "intercom",
    "name": "Intercom",
    "url": "https://mcp.intercom.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Communication",
    "description": "Customer messaging and support data from Intercom.",
    "publisher": "Intercom",
    "official": true
  },
  {
    "slug": "ironclad-contracts",
    "name": "Ironclad Contracts",
    "url": "https://mcp.na1.ironcladapp.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Productivity",
    "description": "Contract lifecycle management with Ironclad.",
    "publisher": "Ironclad",
    "official": true
  },
  {
    "slug": "jam",
    "name": "Jam",
    "url": "https://mcp.jam.dev/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Development",
    "description": "Bug-reporting and debugging capture via Jam.",
    "publisher": "Jam",
    "official": true
  },
  {
    "slug": "jotform",
    "name": "Jotform",
    "url": "https://mcp.jotform.com/mcp-app",
    "transport": "http",
    "auth": "oauth",
    "category": "Productivity",
    "description": "Online form building and submission data from Jotform.",
    "publisher": "Jotform",
    "official": true
  },
  {
    "slug": "linear",
    "name": "Linear",
    "url": "https://mcp.linear.app/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Productivity",
    "description": "Linear MCP server for issues, projects, and cycles.",
    "publisher": "Linear",
    "official": true
  },
  {
    "slug": "lucid",
    "name": "Lucid",
    "url": "https://mcp.lucid.app/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Design",
    "description": "Visual collaboration and diagramming via Lucid.",
    "publisher": "Lucid",
    "official": true
  },
  {
    "slug": "lumin",
    "name": "Lumin PDF",
    "url": "https://mcp.luminpdf.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Productivity",
    "description": "PDF editing and e-signature via Lumin PDF.",
    "publisher": "Lumin PDF",
    "official": true
  },
  {
    "slug": "lusha",
    "name": "Lusha",
    "url": "https://mcp.lusha.com/mcp/claude",
    "transport": "http",
    "auth": "oauth",
    "category": "Marketing",
    "description": "B2B contact and company data enrichment via Lusha.",
    "publisher": "Lusha",
    "official": true
  },
  {
    "slug": "magic-patterns",
    "name": "Magic Patterns",
    "url": "https://mcp.magicpatterns.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Design",
    "description": "AI UI and prototype generation via Magic Patterns.",
    "publisher": "Magic Patterns",
    "official": true
  },
  {
    "slug": "mailerlite",
    "name": "MailerLite",
    "url": "https://mcp.mailerlite.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Marketing",
    "description": "Email marketing campaigns and subscriber data via MailerLite.",
    "publisher": "MailerLite",
    "official": true
  },
  {
    "slug": "make",
    "name": "Make",
    "url": "https://mcp.make.com",
    "transport": "http",
    "auth": "oauth",
    "category": "Other",
    "description": "Workflow automation and scenario orchestration via Make.",
    "publisher": "Make",
    "official": true
  },
  {
    "slug": "mdn",
    "name": "MDN",
    "url": "https://mcp.mdn.mozilla.net/",
    "transport": "http",
    "auth": "none",
    "category": "Development",
    "description": "Web platform documentation from Mozilla MDN (experimental).",
    "publisher": "Mozilla",
    "official": true
  },
  {
    "slug": "mem",
    "name": "Mem",
    "url": "https://mcp.mem.ai/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Memory",
    "description": "Personal notes and knowledge capture via Mem.",
    "publisher": "Mem",
    "official": true
  },
  {
    "slug": "mercury",
    "name": "Mercury",
    "url": "https://mcp.mercury.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Finance",
    "description": "Mercury banking account data via OAuth.",
    "publisher": "Mercury",
    "official": true
  },
  {
    "slug": "mermaid-chart",
    "name": "Mermaid Chart",
    "url": "https://mcp.mermaid.ai/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Development",
    "description": "Diagram generation and rendering via Mermaid Chart.",
    "publisher": "Mermaid Chart",
    "official": true
  },
  {
    "slug": "microsoft-learn",
    "name": "Microsoft Learn",
    "url": "https://learn.microsoft.com/api/mcp",
    "transport": "http",
    "auth": "none",
    "category": "Development",
    "description": "Official Microsoft documentation search via Microsoft Learn.",
    "publisher": "Microsoft",
    "official": true
  },
  {
    "slug": "mintlify",
    "name": "Mintlify",
    "url": "https://mcp.mintlify.com",
    "transport": "http",
    "auth": "none",
    "category": "Development",
    "description": "Documentation search and hosting via Mintlify.",
    "publisher": "Mintlify",
    "official": true
  },
  {
    "slug": "miro",
    "name": "Miro",
    "url": "https://mcp.miro.com/",
    "transport": "http",
    "auth": "oauth",
    "category": "Design",
    "description": "Create and manage Miro boards, diagrams, and visual collaboration content.",
    "publisher": "Miro",
    "official": true
  },
  {
    "slug": "mixpanel",
    "name": "Mixpanel",
    "url": "https://mcp.mixpanel.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Marketing",
    "description": "Query Mixpanel product analytics, events, and user behavior data.",
    "publisher": "Mixpanel",
    "official": true
  },
  {
    "slug": "monday",
    "name": "Monday",
    "url": "https://mcp.monday.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Productivity",
    "description": "Manage monday.com boards, items, and work management workflows.",
    "publisher": "monday.com",
    "official": true
  },
  {
    "slug": "monte-carlo",
    "name": "Monte Carlo",
    "url": "https://integrations.getmontecarlo.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Database",
    "description": "Access Monte Carlo data observability incidents, monitors, and lineage.",
    "publisher": "Monte Carlo",
    "official": true
  },
  {
    "slug": "neon",
    "name": "Neon",
    "url": "https://mcp.neon.tech/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Database",
    "description": "Neon serverless Postgres MCP server for managing databases and projects.",
    "publisher": "Neon",
    "official": true
  },
  {
    "slug": "netdocuments",
    "name": "NetDocuments",
    "url": "https://web-api.us.netdocuments.app/connect/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Productivity",
    "description": "Access and manage NetDocuments legal document management content.",
    "publisher": "NetDocuments",
    "official": true
  },
  {
    "slug": "netlify",
    "name": "Netlify",
    "url": "https://netlify-mcp.netlify.app/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Cloud",
    "description": "Deploy and manage Netlify sites, builds, and configuration.",
    "publisher": "Netlify",
    "official": true
  },
  {
    "slug": "notion",
    "name": "Notion",
    "url": "https://mcp.notion.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Productivity",
    "description": "Notion MCP server for pages, databases, and workspace content.",
    "publisher": "Notion",
    "official": true
  },
  {
    "slug": "oboard",
    "name": "Oboard OKR",
    "url": "https://mcp.oboard.io/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Productivity",
    "description": "OKR management across Jira, Web, and Salesforce via Oboard.",
    "publisher": "Oboard",
    "official": false
  },
  {
    "slug": "openrouter",
    "name": "OpenRouter",
    "url": "https://mcp.openrouter.ai/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Development",
    "description": "Access OpenRouter LLM model routing and inference services.",
    "publisher": "OpenRouter",
    "official": true
  },
  {
    "slug": "otter-ai",
    "name": "Otter.ai",
    "url": "https://mcp.otter.ai/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Productivity",
    "description": "Extract meeting transcripts, summaries, and action items from Otter.ai.",
    "publisher": "Otter.ai",
    "official": true
  },
  {
    "slug": "outreach",
    "name": "Outreach",
    "url": "https://api.outreach.io/mcp/",
    "transport": "http",
    "auth": "oauth",
    "category": "Marketing",
    "description": "Manage Outreach sales engagement sequences and prospect data.",
    "publisher": "Outreach",
    "official": true
  },
  {
    "slug": "parallel",
    "name": "Parallel Search",
    "url": "https://search.parallel.ai/mcp",
    "transport": "http",
    "auth": "bearer",
    "category": "Search",
    "description": "Parallel web search MCP server for AI-grade search results.",
    "publisher": "Parallel",
    "official": true
  },
  {
    "slug": "paypal",
    "name": "PayPal",
    "url": "https://mcp.paypal.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Finance",
    "description": "Manage PayPal payments, invoices, and transactions.",
    "publisher": "PayPal",
    "official": true
  },
  {
    "slug": "peec-ai",
    "name": "Peec AI",
    "url": "https://api.peec.ai/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Marketing",
    "description": "Analyze brand visibility across LLMs with Peec AI.",
    "publisher": "Peec AI",
    "official": true
  },
  {
    "slug": "pg-aiguide",
    "name": "pg-aiguide (TigerData)",
    "url": "https://mcp.tigerdata.com/docs",
    "transport": "http",
    "auth": "none",
    "category": "Database",
    "description": "Access Postgres and TigerData documentation and AI guidance.",
    "publisher": "TigerData",
    "official": true
  },
  {
    "slug": "planetscale",
    "name": "PlanetScale",
    "url": "https://mcp.pscale.dev/mcp/planetscale",
    "transport": "http",
    "auth": "oauth",
    "category": "Database",
    "description": "Manage PlanetScale databases, branches, and queries.",
    "publisher": "PlanetScale",
    "official": true
  },
  {
    "slug": "polar-analytics",
    "name": "Polar Analytics",
    "url": "https://api.polaranalytics.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Marketing",
    "description": "Query Polar Analytics ecommerce metrics and dashboards.",
    "publisher": "Polar Analytics",
    "official": true
  },
  {
    "slug": "postman",
    "name": "Postman",
    "url": "https://mcp.postman.com/minimal",
    "transport": "http",
    "auth": "oauth",
    "category": "Development",
    "description": "Access Postman API collections, workspaces, and requests.",
    "publisher": "Postman",
    "official": true
  },
  {
    "slug": "privacy",
    "name": "Privacy.com",
    "url": "https://mcp.privacy.com",
    "transport": "http",
    "auth": "oauth",
    "category": "Finance",
    "description": "Manage Privacy.com virtual cards and transactions.",
    "publisher": "Privacy.com",
    "official": true
  },
  {
    "slug": "pylon",
    "name": "Pylon",
    "url": "https://mcp.usepylon.com/",
    "transport": "http",
    "auth": "oauth",
    "category": "Communication",
    "description": "Manage Pylon customer support issues and conversations.",
    "publisher": "Pylon",
    "official": true
  },
  {
    "slug": "quartr",
    "name": "Quartr",
    "url": "https://mcp.quartr.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Finance",
    "description": "Access Quartr earnings calls, transcripts, and investor data.",
    "publisher": "Quartr",
    "official": true
  },
  {
    "slug": "railway",
    "name": "Railway",
    "url": "https://mcp.railway.com",
    "transport": "http",
    "auth": "oauth",
    "category": "Cloud",
    "description": "Railway MCP server providing project and deployment context.",
    "publisher": "Railway",
    "official": true
  },
  {
    "slug": "ramp",
    "name": "Ramp",
    "url": "https://ramp-mcp-remote.ramp.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Finance",
    "description": "Manage Ramp spend, cards, and expense data.",
    "publisher": "Ramp",
    "official": true
  },
  {
    "slug": "resy",
    "name": "Resy",
    "url": "https://apigw.americanexpress.com/dining/v1/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Other",
    "description": "Search and book restaurant reservations via Resy.",
    "publisher": "American Express",
    "official": true
  },
  {
    "slug": "sanity",
    "name": "Sanity",
    "url": "https://mcp.sanity.io",
    "transport": "http",
    "auth": "oauth",
    "category": "Development",
    "description": "Manage Sanity CMS content, documents, and datasets.",
    "publisher": "Sanity",
    "official": true
  },
  {
    "slug": "scite",
    "name": "Scite",
    "url": "https://api.scite.ai/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Search",
    "description": "Search scientific citations and research evidence via Scite.",
    "publisher": "Scite",
    "official": true
  },
  {
    "slug": "semrush",
    "name": "Semrush",
    "url": "https://mcp.semrush.com/claude/v1/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Marketing",
    "description": "Access Semrush SEO, keyword, and competitive research data.",
    "publisher": "Semrush",
    "official": true
  },
  {
    "slug": "sentry",
    "name": "Sentry",
    "url": "https://mcp.sentry.dev/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Development",
    "description": "Access Sentry error tracking, issues, and performance data.",
    "publisher": "Sentry",
    "official": true
  },
  {
    "slug": "shopify",
    "name": "Shopify",
    "url": "https://setup.shopify.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Marketing",
    "description": "Connect to a Shopify store to manage products, orders, and storefront data.",
    "publisher": "Shopify",
    "official": true
  },
  {
    "slug": "similarweb",
    "name": "Similarweb",
    "url": "https://mcp.similarweb.com",
    "transport": "http",
    "auth": "oauth",
    "category": "Marketing",
    "description": "Access Similarweb web traffic and digital market intelligence data.",
    "publisher": "Similarweb",
    "official": true
  },
  {
    "slug": "slack",
    "name": "Slack",
    "url": "https://mcp.slack.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Communication",
    "description": "Slack MCP server for messages, channels, and workspace data.",
    "publisher": "Slack",
    "official": true
  },
  {
    "slug": "splice",
    "name": "Splice",
    "url": "https://mcp.splice.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Other",
    "description": "Discover and work with Splice music samples and sounds.",
    "publisher": "Splice",
    "official": true
  },
  {
    "slug": "spotify",
    "name": "Spotify",
    "url": "https://mcp-gateway-external-pilot.spotify.net/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Other",
    "description": "Pilot external gateway for Spotify music data and playback context.",
    "publisher": "Spotify",
    "official": true
  },
  {
    "slug": "square",
    "name": "Square",
    "url": "https://mcp.squareup.com/sse",
    "transport": "sse",
    "auth": "oauth",
    "category": "Finance",
    "description": "Manage Square payments, catalog, and commerce operations.",
    "publisher": "Square",
    "official": true
  },
  {
    "slug": "strava",
    "name": "Strava",
    "url": "https://mcp.strava.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Other",
    "description": "Access Strava athlete activity and fitness data.",
    "publisher": "Strava",
    "official": true
  },
  {
    "slug": "stripe",
    "name": "Stripe",
    "url": "https://mcp.stripe.com",
    "transport": "http",
    "auth": "oauth",
    "category": "Finance",
    "description": "Stripe MCP server for payments, customers, and billing data.",
    "publisher": "Stripe",
    "official": true
  },
  {
    "slug": "stubhub",
    "name": "StubHub",
    "url": "https://open-ai-app.stubhub.net/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Other",
    "description": "Search and book event tickets through StubHub.",
    "publisher": "StubHub",
    "official": true
  },
  {
    "slug": "supabase",
    "name": "Supabase",
    "url": "https://mcp.supabase.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Database",
    "description": "Supabase MCP server for managing Postgres databases and projects.",
    "publisher": "Supabase",
    "official": true
  },
  {
    "slug": "superhuman-mail",
    "name": "Superhuman Mail",
    "url": "https://mcp.mail.superhuman.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Communication",
    "description": "Access and manage email through Superhuman Mail.",
    "publisher": "Superhuman",
    "official": true
  },
  {
    "slug": "surveymonkey",
    "name": "SurveyMonkey",
    "url": "https://mcp.surveymonkey.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Marketing",
    "description": "Create and analyze surveys via SurveyMonkey.",
    "publisher": "SurveyMonkey",
    "official": true
  },
  {
    "slug": "tavily",
    "name": "Tavily",
    "url": "https://mcp.tavily.com/mcp",
    "transport": "http",
    "auth": "bearer",
    "category": "Search",
    "description": "Web search and content extraction via Tavily.",
    "publisher": "Tavily",
    "official": true
  },
  {
    "slug": "todoist",
    "name": "Todoist",
    "url": "https://ai.todoist.net/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Productivity",
    "description": "Manage tasks and projects in Todoist.",
    "publisher": "Todoist",
    "official": true
  },
  {
    "slug": "sketchup",
    "name": "Trimble SketchUp",
    "url": "https://api.sketchup.com/mcp/v1/sketchup/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Design",
    "description": "Trimble SketchUp 3D modeling connector.",
    "publisher": "Trimble",
    "official": true
  },
  {
    "slug": "trivago",
    "name": "Trivago",
    "url": "https://mcp.trivago.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Other",
    "description": "Search and compare hotel prices via Trivago.",
    "publisher": "Trivago",
    "official": true
  },
  {
    "slug": "twilio",
    "name": "Twilio",
    "url": "https://mcp.twilio.com/docs",
    "transport": "http",
    "auth": "none",
    "category": "Communication",
    "description": "Surfaces Twilio API specs and code patterns for messaging and voice.",
    "publisher": "Twilio",
    "official": true
  },
  {
    "slug": "uber",
    "name": "Uber",
    "url": "https://mcp.uber.com/claude/rides-3p/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Other",
    "description": "Request and manage Uber rides.",
    "publisher": "Uber",
    "official": true
  },
  {
    "slug": "uber-eats",
    "name": "Uber Eats",
    "url": "https://mcp.ubereats.com/eats-claude/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Other",
    "description": "Order food delivery through Uber Eats.",
    "publisher": "Uber Eats",
    "official": true
  },
  {
    "slug": "unthread",
    "name": "Unthread",
    "url": "https://app.unthread.io/api/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Communication",
    "description": "Manage support tickets and conversations via Unthread.",
    "publisher": "Unthread",
    "official": true
  },
  {
    "slug": "viator",
    "name": "Viator",
    "url": "https://exp-app-mcp.prod.ep.viator.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Other",
    "description": "Book tours and travel experiences through Viator.",
    "publisher": "Viator",
    "official": true
  },
  {
    "slug": "wordpress-com",
    "name": "WordPress.com",
    "url": "https://public-api.wordpress.com/wpcom/v2/mcp/v1",
    "transport": "http",
    "auth": "oauth",
    "category": "Marketing",
    "description": "Manage WordPress.com sites and content.",
    "publisher": "WordPress.com",
    "official": true
  },
  {
    "slug": "workable",
    "name": "Workable",
    "url": "https://mcp.workable.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Other",
    "description": "Manage recruiting and hiring pipelines via Workable.",
    "publisher": "Workable",
    "official": true
  },
  {
    "slug": "xero",
    "name": "Xero",
    "url": "https://mcp.xero.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Finance",
    "description": "Manage accounting and bookkeeping in Xero.",
    "publisher": "Xero",
    "official": true
  },
  {
    "slug": "yahoo-finance",
    "name": "Yahoo Finance",
    "url": "https://gateway.mcpservers.org/yahoo-finance/mcp",
    "transport": "http",
    "auth": "none",
    "category": "Finance",
    "description": "Yahoo Finance market data MCP server.",
    "publisher": "mcpservers.org",
    "official": false
  },
  {
    "slug": "ziprecruiter",
    "name": "ZipRecruiter",
    "url": "https://api.ziprecruiter.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Other",
    "description": "Search jobs and manage recruiting through ZipRecruiter.",
    "publisher": "ZipRecruiter",
    "official": true
  },
  {
    "slug": "zoominfo",
    "name": "ZoomInfo",
    "url": "https://mcp.zoominfo.com/mcp",
    "transport": "http",
    "auth": "oauth",
    "category": "Marketing",
    "description": "Access ZoomInfo B2B contact and company intelligence data.",
    "publisher": "ZoomInfo",
    "official": true
  }
];
